# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.12.1


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
#v = np.empty(10)
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
v = np.ones(10)
v.itemsize, v.size

(8, 10)

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
v = np.zeros(10)
v[4] = 1
v

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
v = np.arange(10,49)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [17]:
v = np.arange(10,20)
v[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
v = np.array([0,1,2,3,4,5,6,7,8]).reshape((3,3))
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [24]:
v = np.array([1,2,0,0,4,0])
ind = np.arange(len(v))
ind[v > 0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
v = np.identity(3)
v

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [32]:
np.random.rand(3,3,3)

array([[[ 0.24331633,  0.03283309,  0.95050855],
        [ 0.45010855,  0.33957714,  0.73519084],
        [ 0.37988045,  0.03194294,  0.58682356]],

       [[ 0.43116415,  0.56229793,  0.42557032],
        [ 0.57759668,  0.48701006,  0.0260955 ],
        [ 0.60331241,  0.40099801,  0.10197899]],

       [[ 0.23207618,  0.85592243,  0.27417385],
        [ 0.99128248,  0.66554272,  0.43740572],
        [ 0.52418044,  0.46284953,  0.22474175]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
v = np.random.rand(10,10)
v.min(), v.max()

(0.0043175701790012511, 0.99542911479405594)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
v = np.random.rand(30)
v.mean()

0.43423977973224631

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [39]:
rows,cols=8,9
v = np.zeros((rows,cols))
v[0,:] = 1
v[rows-1,:] = 1
v[:,0] = 1
v[:, cols-1] = 1
v

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [54]:
v = np.random.randint(50, size=(4,5))
print(v)
print()
# one zeros pad above, 2 zeros pad bottom
# three zeros pad left, 4 zeros pad right
print(np.pad(v,((1,2),(3,4)), 'constant'))
print()
print(np.pad(v,((1,1),(1,1)), 'constant'))

[[13  9 45 49 36]
 [24  3 35 43 24]
 [47 34 45 31  8]
 [30 19 25 17  0]]

[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 13  9 45 49 36  0  0  0  0]
 [ 0  0  0 24  3 35 43 24  0  0  0  0]
 [ 0  0  0 47 34 45 31  8  0  0  0  0]
 [ 0  0  0 30 19 25 17  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]

[[ 0  0  0  0  0  0  0]
 [ 0 13  9 45 49 36  0]
 [ 0 24  3 35 43 24  0]
 [ 0 47 34 45 31  8  0]
 [ 0 30 19 25 17  0  0]
 [ 0  0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [59]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
v = np.zeros((5,5))

np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
v = np.zeros((8,8))
v[::2,::2] = 1
v[1::2,1::2] = 1
v

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [23]:
np.info(np.unravel_index)
np.unravel_index(100, (6,7,8))

unravel_index(indices, dims, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``dims``. Before version 1.6.0,
    this function accepted just one index value.
dims : tuple of ints
    The shape of the array to use for unraveling ``indices``.
order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 13], (7,6), order='F')
(array([3, 6, 6]), array([4, 5, 1]))

>>> np.unravel_index

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
v = np.array([[0,1],[1,0]])
np.tile(v,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [41]:
v = np.random.randint(100,size=(5,5))
(v - v.min()) / (v.max() - v.min()) 

array([[ 0.94680851,  0.08510638,  0.31914894,  0.44680851,  0.12765957],
       [ 0.85106383,  0.91489362,  0.4893617 ,  0.        ,  0.07446809],
       [ 0.9893617 ,  0.59574468,  0.53191489,  0.92553191,  0.79787234],
       [ 0.39361702,  1.        ,  0.03191489,  0.0106383 ,  0.95744681],
       [ 0.86170213,  0.19148936,  0.04255319,  0.08510638,  0.05319149]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [49]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
a @ b

array([[ 1.65389021,  1.0952761 ],
       [ 0.93922466,  0.62382028],
       [ 0.63873923,  0.45540622],
       [ 1.41329376,  0.99876331],
       [ 1.35444612,  0.86235782]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [67]:
v = np.random.randint(20, size=10)
v[np.where(np.logical_and(v>=3, v<=8))] *= -1
v

array([18, 12, -3, 15, 17, -7, 14, 14, 16, 17])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [75]:
#print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
(range(5),-1)

10


(range(0, 5), -1)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [86]:
np.array([np.nan]).astype(int).astype(float)

array([ -2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [94]:
v = np.random.rand(3,3)
np.copysign(-1.3000,1)

1.3

#### 30. How to find common values between two arrays? (★☆☆)

In [110]:
a = np.random.randint(10,size=(2,5))
b = np.random.randint(10, size=(5,2))
print('a=\n',a)
print('b=\n',b)
np.intersect1d(a.flatten(), b.flatten())

a=
 [[0 3 9 1 8]
 [8 9 4 9 5]]
b=
 [[3 8]
 [1 7]
 [3 1]
 [1 1]
 [6 3]]


array([1, 3, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [111]:
np.info(np.seterr
       )

 seterr(all=None, divide=None, over=None, under=None, invalid=None)

Set how floating-point errors are handled.

Note that operations on integer scalar types (such as `int16`) are
handled like floating point, and are affected by these settings.

Parameters
----------
all : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Set treatment for all types of floating-point errors at once:

    - ignore: Take no action when the exception occurs.
    - warn: Print a `RuntimeWarning` (via the Python `warnings` module).
    - raise: Raise a `FloatingPointError`.
    - call: Call a function specified using the `seterrcall` function.
    - print: Print a warning directly to ``stdout``.
    - log: Record error in a Log object specified by `seterrcall`.

    The default is not to change the current behavior.
divide : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Treatment for division by zero.
over : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
  

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [116]:
np.info(np.emath.sqrt)

 sqrt(x)

Compute the square root of x.

For negative input elements, a complex value is returned
(unlike `numpy.sqrt` which returns NaN).

Parameters
----------
x : array_like
   The input value(s).

Returns
-------
out : ndarray or scalar
   The square root of `x`. If `x` was a scalar, so is `out`,
   otherwise an array is returned.

See Also
--------
numpy.sqrt

Examples
--------
For real, non-negative inputs this works just like `numpy.sqrt`:

>>> np.lib.scimath.sqrt(1)
1.0
>>> np.lib.scimath.sqrt([1, 4])
array([ 1.,  2.])

But it automatically handles negative inputs:

>>> np.lib.scimath.sqrt(-1)
(0.0+1.0j)
>>> np.lib.scimath.sqrt([-1,4])
array([ 0.+1.j,  2.+0.j])


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [124]:
one_day = np.timedelta64(1,'D')
today = np.datetime64('today') 
yesterday = today - one_day 
tomorrow  = today + one_day
print(yesterday, today, tomorrow)

2017-08-28 2017-08-29 2017-08-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [1]:
import numpy as np
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [14]:
v = np.random.rand(10) + np.random.randint(10,size=10)
print(v - v % 1)
print(np.ceil(v) - 1)
print(np.floor(v))
print(v.astype(int))
print(np.trunc(v))

[ 4.  3.  8.  0.  8.  8.  6.  8.  1.  2.]
[ 4.  3.  8.  0.  8.  8.  6.  8.  1.  2.]
[ 4.  3.  8.  0.  8.  8.  6.  8.  1.  2.]
[4 3 8 0 8 8 6 8 1 2]
[ 4.  3.  8.  0.  8.  8.  6.  8.  1.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [21]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [25]:
def gen():
    for x in range(10):
        yield x
z = np.fromiter(gen(), dtype=float, count=10)
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [32]:
v = np.linspace(0,1,20,endpoint=False)[1:]
print(v)

[ 0.05  0.1   0.15  0.2   0.25  0.3   0.35  0.4   0.45  0.5   0.55  0.6
  0.65  0.7   0.75  0.8   0.85  0.9   0.95]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
np.sort(np.random.rand(10))

array([ 0.11173071,  0.33612346,  0.35406161,  0.37739617,  0.61969094,
        0.63767448,  0.68050719,  0.78781961,  0.84266532,  0.93397965])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [34]:
np.add.reduce(np.random.rand(5))

3.1657337867419173

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
np.array_equal(A,B)

#### 43. Make an array immutable (read-only) (★★☆)

In [37]:
v = np.zeros(5)
v.flags.writeable = False
v[0]=10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)